# Generated by Django 3.2.18 on 2023-03-05 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20230220_1804'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='hash',
            field=models.CharField(blank=True, max_length=66, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='txId',
            field=models.CharField(blank=True, max_length=66, null=True),
        ),
    ]
