# Generated by Django 3.2.18 on 2023-03-25 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_code'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Code',
        ),
    ]
